name: the_watcher_blogs
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  fpdart: ^1.1.1
  intl: ^0.20.2
  jaspr: ^0.19.0
  jaspr_router: ^0.7.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.19.0
  jaspr_lints: ^0.3.1
  lints: ^5.0.0

jaspr:
  mode: server

